### ISSUE TITLE
a library should not "println", but return an error type

### ISSUE THREAD

**Issue by getreu** [bekker/msgbox-rs#13]
Thank you for this useful crate.

It would be very useful to know if the message box finally popped up or if there had been some error.

Please consider the following extract of  `linux.rs`.

```rust
pub fn create(title:&str, content:&str, icon_type:IconType) {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        println!("{}", content);
        return;
    }
```

Instead of dumping on the console with `println!()` I suggest returning some error type. Otherwise there is no way for the caller to know if something went wrong!

**Comment by bekker** [comment]
You're absolutely right. I'll look into it when I can afford.
Or a PR would be welcome!

**Comment by getreu** [comment]
Just a thought about your API to share: 

In addition to the above, maybe it is possible to expose the result of `gtk::init()` also as separate method in you API? 

With this method the caller could check in advance, if a graphic environment is available, without opening a window yet. I guess most people use your crate like me, without pulling any GTK libraries directly. In my application [^1 ] I could then adjust the way I communicate with the user.
[^1]:  https://github.com/getreu/tp-note

**Comment by getreu** [comment]
Maybe the above suggestion would make the API too complicated. As a workaround one could check for the environment variable `DISPLAY` to check if some Xserver is running.

**Comment by bekker** [comment]
I think we should be careful of directly exposing the result of ```gtk::init()``, since that's platform-dependent API.
Maybe making a custom Error for such situation (initialization failed regardless reason) and throwing it?

**Comment by bekker** [comment]
I've merged a [commit](https://github.com/bekker/msgbox-rs/commit/68257bcffe74492b5210ad46c8146d9a25315b15) into master.

Now `create()` method returns `Result<(), MsgBoxCreationError>` so that caller know whether the window has been created successfully.

The availability method you mentioned, it seemed not viable for other platforms (Windows, MacOS...) so I'd like to put it on hold for now.

I'm planning to release this commit after this weekend if there's no issue.

Thanks.

**Comment by getreu** [comment]
Thanks a lot for your fast action!
BTW: your error type seems too complicated to me: 

```rust
#[derive(Debug)]
pub struct MsgBoxCreationError<'a> {
    pub title: &'a str,
    pub content: &'a str,
    pub icon_type: IconType,
}
```

All information it contains, is already known to the caller, thus useless. An error type should only abstract the error state(s) and eventually the reasons that lead to these error states. Nothing else. Besides, very often it is a good idea to forward error types of foreign libraries. Here my suggestion (using [thiserror](https://docs.rs/thiserror/1.0.20/thiserror/)):

```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum MsgBoxError {
    #[error("the window creation failed")]
    Create(#[from] glib::BoolError),
    #[error("unknown reason")]
    Unknown,
}
```

**Comment by bekker** [comment]
I've changed the error as following:

```rust
#[derive(thiserror::Error, Debug)]
pub enum MsgBoxError {
    #[error("failed to create a message box")]
    Create{#[source] source: Option<Box<dyn error::Error>>},
}
```

I wanted to implement `source()` of `Error` trait while being platform-independent.

I've considered [anyhow](https://crates.io/crates/anyhow) but was doubtful that using it in a library crate is a good idea, so just wrapped with a `Box`.

**Comment by getreu** [comment]
Yes, anyhow is not a good idea for libraries. What is the advantage of `#[source]` over  `#[from]` ?

**Comment by bekker** [comment]
You can't define another error enum with same source type with `#[from]`.

```rust
#[derive(thiserror::Error, Debug)]
pub enum MsgBoxError {
    #[error("failed to create a message box")]
    Create{#[from] source: Option<Box<dyn error::Error>>},
    #[error("failed to create a message box")]
    Unknown{#[from] source: Option<Box<dyn error::Error>>},
}
```
```
error: cannot derive From because another variant has the same source type
  --> src/common.rs:21:13
   |
21 |     Unknown{#[from] source: Option<Box<dyn error::Error>>},
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

While `#[source]` can.

Right now there's only one enum but who knows?

Actually I think there's no advantage of `#[from]` over `#[source]` since the source type is a Box of generic Error type.
Could you tell me one if any? I'm not so experienced in Rust codes :)

**Comment by getreu** [comment]
It seems, that by boxing your Error, you loose the advantage of error types. It is better to forward the error type of the library. Then the caller can decide what to do.
Look in `linux::create()` how elegant it becomes!

This is how a typical error console dump looks now, when called in debug mode without X11 running:

```
     Running `target/debug/examples/hello_world`
Unable to init server: Could not connect: Connection refused
failed to create a message box (type: Error, title: "Error", content: "Error occured at hello_world.rs:5.
Terminating..")
cause: Failed to initialize GTK
```

BTW: I suggest `cargo fmt` to format your code. It saves a lot time and gives nice results. Do you want me to run it?

**Comment by bekker** [comment]
Thanks for the PR!
I'll look into formatting codes and dependency updates.
And I like the conciseness of `linux::create()`.

But `glib` crate being a common dependency seems not right.
For Windows and macOS `glib` crate is not necessary, so adding it for the error handling seems to be an overkill to me.
(For Windows you can't even build if glib is not installed on the system.. AppVeyor CI has also failed)

And the source error of `MsgBoxError::Create` is not necessarily `glib::BoolError`. I thought about adding `MsgBoxError::GtkError` or something (for every platform... WinApiError, CocoaError etc) but in order to maintain the simplicity I just wrapped the Error with Box.

If this crate was gtk-specific it would be perfect but I want this crate be platform-independent as much as possible (And I think that's the whole meaning of this crate) even if the codes being a little bit dirty.

**Comment by getreu** [comment]
> But glib crate being a common dependency seems not right.
> For Windows and macOS glib crate is not necessary, so adding it for the error handling seems to be an overkill to me.

The linker adds only what is needed. Anyway, I removed the glib dependency for most targets. Please have a look at my
latest commit. 

> If this crate was gtk-specific it would be perfect but I want this crate be platform-independent as much as possible (And I think that's the whole meaning of this crate) even if the codes being a little bit dirty.

Using error types does not force anybody to use it. But for some it provides precious information.

Concerning your crate, I also think  it makes sense to return an own error type here. Even if it will not be used today with some targets. This can change from release to release. And as I mentioned, nobody is forced to use it and error types do not introduce platform dependency.

> even if the codes being a little bit dirty.

There is no reason here, to expose an unprofessional API. As mentioned in my last comment above, it is not a good idea to box error types in a library. For those who do not rely on the error, it does not change anything, for those who do it makes their life more complicated.

Best regards

**Comment by getreu** [comment]
All checks passed with last commit.
BTW: besides `cargo fmt` `cargo upgrade` is also worth to have a look at. I use it a lot.

**Comment by bekker** [comment]
Thank you for the edit! I've added some comments on the PR, please check it out.
